import {
	AntDesignOutlined,
	ApartmentOutlined,
	AppstoreOutlined,
	CloudOutlined,
	ContainerOutlined,
	CopyrightOutlined,
	DashboardOutlined,
	DatabaseOutlined,
	ExperimentOutlined,
	EyeOutlined,
	FileTextOutlined,
	FolderOpenOutlined,
	HomeOutlined,
	IssuesCloseOutlined,
	LockOutlined,
	MenuOutlined,
	MinusSquareOutlined,
	NodeExpandOutlined,
	ProjectOutlined,
	SafetyOutlined,
	SettingOutlined,
	SisternodeOutlined,
	StopOutlined,
	SubnodeOutlined,
	TeamOutlined,
	ToolOutlined,
	UnorderedListOutlined,
	UserOutlined,
} from "@ant-design/icons";
import { EmbeddedIcon, ExternalIcon, OutsidePageIcon, ProfileCardIcon, ServerErrorIcon } from "./local-icons";
import { RiAccountCircleLine, RiReactjsLine, RiUserSettingsLine } from "./ri";

/**
 * Icons used in the menu.
 */
export const menuIcons: Record<string, any> = {
	EmbeddedIcon,
	HomeOutlined,
	SafetyOutlined,
	CloudOutlined,
	FileTextOutlined,
	LockOutlined,
	EyeOutlined,
	NodeExpandOutlined,
	SisternodeOutlined,
	SubnodeOutlined,
	OutsidePageIcon,
	AntDesignOutlined,
	ContainerOutlined,
	ExternalIcon,
	RiReactjsLine,
	SettingOutlined,
	UserOutlined,
	TeamOutlined,
	MenuOutlined,
	ApartmentOutlined,
	RiAccountCircleLine,
	ProfileCardIcon,
	RiUserSettingsLine,
	CopyrightOutlined,
	ToolOutlined,
	ExperimentOutlined,
	ProjectOutlined,
	UnorderedListOutlined,
	AppstoreOutlined,
	DashboardOutlined,
	DatabaseOutlined,
	FolderOpenOutlined,
	IssuesCloseOutlined,
	MinusSquareOutlined,
	StopOutlined,
	ServerErrorIcon,
};
